# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Minh Nguyen
title: Electrical Engineer
email: enrminhnguyen@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  mbd4ever
linkedin_username: Minh Nguyen

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 Welcome to my humble resume. I'm a newly grad Electrical Engineering student with 2 years of teaching experience in lower level engineer courses as well as promised a full scholarship to finish the MS program from West Virginia University.
  I am an easy going, fun loving guy who has seen his fair share of hardship due to my 10 years journey in the US. Fluent in both English and Vietnamese and hard work are my strong points.


content:
  - title: Project # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
          title: Cubesat Project
        description: | # this will include new lines to allow paragraphs
          I was the leader of the CubeSat Project team. The project focused on launching a microprocessor into space via the
CubeSat to study the effect of space on the chip. I was tasked with managing the ground station where we had to
build a system similar to the one onboard the CubeSat and run it in parallel with the one in space. The data of both
the ground station and space were compared to learn how space might have effected our chip.
The project required a lot of data processing, time managing and researching, it also helped me get better in learning
how to use google and Matlab.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: College Lab Instructor
        caption: September 2019 - May 2021
        quote: >
          There's no introduction like the introduction to engineering, it is the pinnacle of your engineering career because it only goes downhill from there.
        description: | # this will include new lines to allow paragraphs
            I taught as lab instructor for an introduction class to computer engineer. The class introduced everything a computer/electrical engineer student would need: logic gates, coding in VHDL, circuit designs, and most importantly, the realization that all of these machines work because of math and formula, not magic dust.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: West Virginia University
        caption: 2018- 2021
        sub_title: BS Electrical Engineer
       
        description: | # this will include new lines to allow paragraphs
         I spent most of my time here trying my best to succeed while balancing between my part time job to pay the bill and making new connections within the school premise. I ended up earning myself a spot in the Robotic Club where I had to come up with different test scenarios ( different terrains, environments, etc.) which was really fun and a good starting point for my resreach on the CubeSat projecet later down the line.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in researching and machinary some of my other interests and hobbies are:
      - Video games ( obviously )
      - Billiards
      - Food, just food
      - Small talks, big talks, medium talks, I just love a good conversations.

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
